
data_config:
  train: True
  dataset_dir: '/dataset'
  batch_size: 128
  num_workers: 0
  validation_split: 0.1
  seed_value: 5
  add_noise_spectrum: True

train_config:
  epochs: 5
  learning_rate: 3.0e-4
  early_stopping: True
  stopping_patience: 20

model_config:
  num_heads : 7
  num_encoder_layers : 10
  dim_feedforward: 868
  dropout: 0.1
  fc_layers: 400

inference_config:
  result_dir: '/results/'
  base_ckpt: '/results/NeutronStar/epoch=4-val_loss=0.4491.ckpt'
  model_ckpt: '/results/NeutronStar/epoch=113-step=52895.ckpt'
  visualise: True