
data_config:
  dataset_dir: '/dataset'
  batch_size: 2560
  num_workers: 8
  validation_split: 0.1
  seed_value: 5
  nH_c: "true"
  logTeff_c: "true"
  dist_c: "true"
  add_noise_spectrum: True
  
result_dir: '/results/'

train_config:
  epochs: 5
  learning_rate: 3.0e-4
  early_stopping: True
  stopping_patience: 20
model_config:
  num_heads : 7
  num_encoder_layers : 10
  dim_feedforward: 868
  dropout: 0.1
  fc_layers: 400