
data_config:
  mini_ns: True
  dataset_dir: '/dataset'
  batch_size: 128
  num_workers: 0
  validation_split: 0.1
  test_split: 0.2
  seed_value: 5
  nH_c: "true"
  logTeff_c: "true"
  dist_c: "true"
  add_noise_spectrum: True
  
result_dir: '/results/'

train_config:
  epochs: 10
  learning_rate: 3.0e-4

model_config:
  num_heads : 7
  num_encoder_layers : 5
  dim_feedforward: 1024
  dropout: 0.1
  fc_layers: 200